apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-web
  namespace: <namespace>
spec:
  template:
    metadata:
      labels:
        app: python-web
    spec:
      containers:
      - name: python-web
        image: danielma911/python-web-local:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: branch
          value: <BRANCH_NAME>

---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: <namespace>
  labels:
    app: python-web
spec:
  selector:
    app: python-web
  type: NodePort
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    nodePort: <PORT>
